name: Chromium OS image builder
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu_latest
    steps:
    - uses: actions/checkout@v2
    - name: Build amd64-generic image
      run: bash ./build.sh

    - uses: actions/upload-artifact@v2
      with:
        name: Chromium OS amd64-generic image
        path: src/build/images/amd64-generic/latest/chromiumos_qemu_image.bin 
